# Generated by Django 2.0 on 2018-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='img',
            field=models.ImageField(default='assets/img/no-img.jpg', upload_to='assets/img/'),
        ),
    ]
