# Generated by Django 2.0 on 2018-01-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180107_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='img',
            field=models.ImageField(default='img/no-img.jpg', upload_to='img/'),
        ),
    ]
